tags:
  - name: /api/user
    description: Rutas relacionadas con el proceso de login, autenticación y gestión de usuarios.
  - name: /api/categories
    description: Rutas relacionadas con la gestión del recurso Categories.
  - name: /api/authors
    description: Rutas relacionadas con la gestión del recurso Authors
  - name: /api/books
    description: Rutas relacionadas con la gestión del recurso Books
  - name: /api/borrowings
    description: Rutas relacionadas con la gestión del recurso Borrowings, aún por definir

/login:
  post:
    tags:
      - /api/user
    description: Recibe credenciales de usuario y genera un token temporal.
    summary: Autentica al usuario y genera un JWT.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
                description: Nombre de usuario, debe tener entre 1 y 15 caracteres.
                example: usuario123
              password:
                type: string
                description: Contraseña secreta de usuario, de preferencia usar una fuerte. Debe tener entre 1 y 100 caracteres. No hay requisitos especiales.
    responses:
      201:
        description: Autenticación exitosa, se devuelve un token JWT.
        content: 
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Token de autenticación. Se debe guardar en el navegador y mandar en el header de las peticiones http del usuario, ya que se usa para autenticar su identidad. Dura 20 minutos.
                username:
                  type: string
                  description: Nombre del usuario que generó el token. Se puede guardar en el navegador para presentar una web dinámica basada en el usuario activo.
                  example: usuario123
                usertype:
                  type: string
                  description: Tipo de usuario autenticado, puede ser admin o client.
                  example: admin
      400:
        description: Error del cliente a la hora de mandar los datos.
      401:
        description: Credenciales incorrectas.
      500:
        description: Error interno del servidor o problema en la consulta SQL.

/register:
  post:
    tags:
      - /api/user
    description: Ruta de administración la cual permite crear un usuario en base a un username, password y usertype, es usada por un administrador para crear un nuevo usuario que puede ser otro administrador.
    summary: Ruta para crear nuevos usuarios, puede crear administradores.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - username
              - password
              - usertype
            properties:
              username:
                type: string
                description: Nombre del usuario, no debe ser mayor a 15 caracteres y no puede estar vacío.
                example: usuario123
              password:
                type: string
                description: Contraseña de usuario, no puede estar vacío y debe ser menor a 100 caracteres. No tiene requisitos especiales.
                example: soyunpassword12345
              usertype:
                type: string
                description: Es el tipo de usuario, definirá los privilegios y acceso a rutas de la API, así como debería limitar su acceso a la aplicación. Solo puede ser admin o client.
                example: admin
    responses:
      200:
        description: La ruta ha funcionado sin errores y un nuevo usuario ha sido creado.
      400:
        description: Hubo un error por parte del usuario y se puede volver a mandar la petición para solucionarlo.
      500:
        description: Hubo un error interno en el servidor por un error mal manejado o alguna parte de la arquitectura no funciona. Se debe esperar a que se arregle.